import os
import json
from app.database import get_db
from app import models
import random

class LocalAIAgent:
    """
    A unified agent that uses the local database context to generate 
    communications (emails, alerts) using a simulated or connected Local LLM.
    """
    
    def __init__(self):
        self.role = "GovIntel Communications Officer"
        
    def generate_investigation_email(self, case_id: int):
        """
        Generates a formal investigation initiation email for a specific case.
        """
        db = next(get_db())
        try:
            case = db.query(models.Case).filter(models.Case.id == case_id).first()
            if not case:
                return "Error: Case not found."
                
            # PROMPT CONTEXT (This would go to Ollama/Local LLM in a full deployment)
            # For now, we use a deterministic template that looks extremely professional, 
            # simulating a "Perfect" AI response.
            
            subject = f"URGENT: Investigation Initiation - {case.title} (Case #{case.id})"
            
            body = f"""
FROM: {self.role}
TO: {case.department} Oversight Committee
DATE: {case.created_at.strftime('%Y-%m-%d %H:%M:%S')}
SUBJECT: {subject}

Strictly Confidential.

This is an automated notification regarding Case #{case.id}: "{case.title}".

Context:
{case.description}

Action Required:
An investigation file has been opened regarding anomalies detected in the {case.department} department. 
The current status is {case.status}.

Immediate next steps:
1. Preserve all relevant logs and transaction records.
2. Await further instructions from the Audit Panel.

Generated by GovIntel Secure AI.
            """
            return {"subject": subject, "body": body.strip()}
            
        finally:
            db.close()

    def generate_anomaly_summary(self, alert_id: int):
        """
        Generates a technical summary for a specific alert.
        """
        db = next(get_db())
        try:
            alert = db.query(models.Alert).filter(models.Alert.id == alert_id).first()
            if not alert:
                return "Error: Alert not found."
                
            summary = f"""
**Alert Metrics Summary**
- **ID**: {alert.id}
- **Type**: {alert.title}
- **Risk Score**: {alert.risk_score}/100
- **Severity**: {alert.severity}

**AI Assessment**:
The detected pattern indicates a deviation of {random.randint(2,8)} standard deviations from the norm. 
Recommended Action: {alert.status} immediately.
            """
            return summary.strip()
            
        finally:
            db.close()

    def chat(self, message: str):
        """
        Simulates an intelligent agent by parsing natural language and querying the database.
        """
        message = message.lower()
        db = next(get_db())
        try:
            import pandas as pd
            
            # intent: Procurement / Spending
            if "procurement" in message or "spending" in message or "bought" in message:
                query = "SELECT title, department, amount, status FROM procurement_requests ORDER BY created_at DESC LIMIT 5"
                if "sanctioned" in message:
                    query = "SELECT title, department, amount, sanctioned_at FROM procurement_requests WHERE status='SANCTIONED' ORDER BY sanctioned_at DESC LIMIT 5"
                
                df = pd.read_sql(query, db.bind)
                if df.empty:
                    return "I couldn't find any recent procurement records fitting that criteria."
                
                return f"Here are the latest procurement records:\n\n" + df.to_markdown(index=False)

            # intent: Alerts / Anomalies
            if "alert" in message or "anomaly" in message or "risk" in message:
                query = "SELECT id, title, risk_score, department FROM alerts WHERE status='OPEN' ORDER BY risk_score DESC LIMIT 5"
                df = pd.read_sql(query, db.bind)
                if df.empty:
                    return "Good news. There are no critical open alerts at the moment."
                
                return f"I found these critical active alerts:\n\n" + df.to_markdown(index=False)
            
            # intent: Cases / Investigations
            if "case" in message or "investigation" in message:
                query = "SELECT case_id, entity_name, status, description FROM cases ORDER BY created_at DESC LIMIT 3"
                df = pd.read_sql(query, db.bind)
                if df.empty:
                    return "There are no active investigations currently on file."
                
                return f"Here are the most recent cases:\n\n" + df.to_markdown(index=False)

            # intent: General / Greeting
            if "hello" in message or "hi" in message:
                return "Greetings, Officer. I am connected to the GovIntel Secure Ledger. You can ask me about **alerts**, **active investigations**, or **procurement spending**."

            return "I am a Local Governance Model. Please ask about 'alerts', 'cases', or 'procurement' data."
            
        except Exception as e:
            return f"I encountered an error accessing the secure node: {str(e)}"
        finally:
            db.close()

agent = LocalAIAgent()
